source 'https://rubygems.org'

gem 'chronic', '~> 0.10.2'
gem 'cloudinary'
gem 'github-linguist', '~> 5.3'
gem 'licensee', '~> 9.9'
gem 'nokogiri', '1.10.4'
gem 'octokit', '~> 4.8'
gem 'rack', '>= 2.0.6'
gem 'rest-client', '~> 2.0'
gem 'serrano'
gem 'sidekiq'
gem 'sidekiq_status'
gem 'sinatra', '2.0.2'
gem 'sinatra-contrib', '2.0.2'
gem 'twitter'
gem 'unicorn', '5.3.1'
gem 'pry-byebug'
gem 'whedon', :git => 'https://github.com/openjournals/whedon.git', :ref => '05bc17e752deec8004b37cd5c1ca2b364546432c'

group :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'webmock'
end
